# Generated by Django 6.0.3 on 2026-03-10 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('wikipedia', 'Wikipedia'), ('gutenberg', 'Project Gutenberg')], db_index=True, max_length=50)),
                ('original_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('full_text', models.TextField(blank=True, null=True)),
                ('categories', models.TextField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('wikipedia', 'Wikipedia'), ('gutenberg', 'Project Gutenberg')], max_length=50)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_documents', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-loaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('diff', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='data_master.document')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_master.documentrevision')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_master.source')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_master.source'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['source_type', 'is_active'], name='data_master_source__abe70f_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['slug'], name='data_master_slug_55cb24_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['title'], name='data_master_title_d4db52_idx'),
        ),
    ]
