# Generated by Django 6.0.3 on 2026-03-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('wikipedia', 'Wikipedia'), ('gutenberg', 'Project Gutenberg'), ('wikibooks', 'Wikibooks'), ('wikivoyage', 'Wikivoyage'), ('iFixit', 'iFixit'), ('arxiv', 'arXiv')], max_length=50),
        ),
    ]
