# Generated by Django 6.0.3 on 2026-03-15 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_master', '0002_alter_source_source_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='source_type',
            field=models.CharField(choices=[('wikipedia', 'Wikipedia'), ('gutenberg', 'Project Gutenberg'), ('wikibooks', 'Wikibooks'), ('wikivoyage', 'Wikivoyage'), ('ifixit', 'iFixit'), ('arxiv', 'arXiv')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('wikipedia', 'Wikipedia'), ('gutenberg', 'Project Gutenberg'), ('wikibooks', 'Wikibooks'), ('wikivoyage', 'Wikivoyage'), ('ifixit', 'iFixit'), ('arxiv', 'arXiv')], max_length=50),
        ),
        migrations.CreateModel(
            name='PdfTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('colour', models.CharField(default='#f59e0b', max_length=7)),
                ('icon', models.CharField(default='🏷️', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PdfTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_path', models.CharField(max_length=500)),
                ('pdf_name', models.CharField(max_length=500)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_assignments', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='data_master.pdftag')),
            ],
            options={
                'ordering': ['pdf_name'],
                'unique_together': {('tag', 'pdf_path')},
            },
        ),
    ]
