# Generated by Django 6.0.3 on 2026-03-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('net1_online', models.BooleanField(default=False)),
                ('cpu_percent', models.FloatField(default=0)),
                ('ram_percent', models.FloatField(default=0)),
                ('ram_used_gb', models.FloatField(default=0)),
                ('ram_total_gb', models.FloatField(default=0)),
                ('disk_percent', models.FloatField(default=0)),
                ('disk_used_gb', models.FloatField(default=0)),
                ('disk_total_gb', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
