# Generated by Django 6.0.3 on 2026-03-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_logger', '0002_activitylog_delete_systemsnapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('page_view', 'Page View'), ('prompt', 'LLM Prompt'), ('search', 'Search'), ('download', 'Download'), ('sync', 'Data Sync'), ('llm_manage', 'LLM Management'), ('login', 'Login'), ('logout', 'Logout'), ('note_create', 'Note Created'), ('note_edit', 'Note Edited'), ('note_comment', 'Note Comment'), ('other', 'Other')], default='page_view', max_length=20),
        ),
    ]
