# Generated by Django 6.0.3 on 2026-03-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notetag',
            name='icon',
            field=models.CharField(default='🏷️', max_length=10),
        ),
    ]
