# Generated by Django 6.0.3 on 2026-03-14 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notetag_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotePersonalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_note_tags', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_tags', to='notes.note')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_assignments', to='notes.notetag')),
            ],
            options={
                'unique_together': {('note', 'tag', 'assigned_by')},
            },
        ),
    ]
