# Generated by Django 6.0.3 on 2026-03-08 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikiDump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_pages', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-loaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('full_text', models.TextField(blank=True)),
                ('categories', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dump', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='data_master.wikidump')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WikiRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('diff', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='data_master.wikidump')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='data_master.wikipage')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_master.wikirevision')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['title'], name='data_master_title_b22f19_idx'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['slug'], name='data_master_slug_b1e128_idx'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['page_id'], name='data_master_page_id_07239b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wikirevision',
            unique_together={('page', 'version')},
        ),
    ]
