# Generated by Django 6.0.3 on 2026-03-14 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notepersonaltag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteimage',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='notes.note'),
        ),
    ]
